- name: print the msg
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: print
      debug:
        msg: "Print the message"

    - name: check uptime
      shell: uptime
      register: output

    - name: print uptime
      debug:
        msg: "uptime of server is {{ output.stdout }}"

    - name: Install docker
      dnf:
        name: docker
        state: installed

    - name: start docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
